language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

matrix:
    allow_failures:
        - php: hhvm

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
